const pattDigit = /[0-9]/;
const pattOpera = /^[\+\*\-\/\\\=]$/;
var valor1 = "0";
var valor2 = "\\";
var valor3 = "=";
console.log(pattDigit.test(valor1));
console.log(pattOpera.test(valor2));
console.log(pattOpera.exec(valor2));
console.log(pattOpera.exec(valor2) ? pattOpera.exec(valor2)[0] : "es_nulo");
console.log(pattOpera.test(valor3));
console.log(pattOpera.exec(valor3) ? pattOpera.exec(valor3)[0] : "es_nulo");
const pTestTlfNac1 = /^\d{9}$/;
const pTestTlfNac2 = /^[0-9]{9}$/;
var tlfNac = "959330011";
console.log("Tlf. nacional: " + tlfNac + " es " + pTestTlfNac1.test(tlfNac));
console.log(pTestTlfNac2.exec(tlfNac) ? pTestTlfNac2.exec(tlfNac)[0] : " es_nulo");
const pTestTlfInt = /^\(\+\d{2,3}\)\d{9}$/;
var tlfInt = "(+34)955000117";
console.log("Tlf. internacional: " + pTestTlfInt.test(tlfInt));
const pTestFecha = /^\d{2}\\\d{2}\\\d{4}$/;
var fecha = "01\\10\\2016";
console.log("Fecha (dd\\mm\\aaaa): " + fecha + " " + pTestFecha.test(fecha));
const pTestCpostal = /^\d{5}$/;
const pTestCpostal2 = /^\d{2}\.\d{3}$/;
var cpostal = "21410";
var cpostal2 = "21.410";
console.log("Codigo postal: (nnnnn): " + cpostal + " " + pTestCpostal.test(cpostal));
console.log("Codigo postal: (nn.nnn): " + cpostal2 + " " + pTestCpostal2.test(cpostal2));
const patteMail = /^(.+\@.+\..+)$/;
const myEmail = /^(.{2,10}\@.{3,10}\..{2,3})$/;
const myEmail2 = /^(([a-z]|[A-Z]).{1,10}\@.{3,10}\..{2,3})$/;
const myEmail3 = /^(([a-z]|[A-Z])[\w-\.]{1,10}[a-zA-Z]{1}\@.{3,10}\..{2,3})$/;
var email = "g234-678-9@gmail.com";
console.log("e-mail: " + email + " " + myEmail.test(email));
console.log("e-mail: " + email + " " + myEmail2.test(email));
console.log("e-mail: " + email + " " + myEmail3.test(email));
const pNumentero1 = /^(\+|\-)?\d+$/;
const pNumentero2 = /^[+-]?\d+$/;
const pNumentero3 = /^(\-)?[0-9]{2,5}$/;
var numEntero = "-023";
console.log("Nº entero: " + numEntero + " " + pNumentero1.test(numEntero));
console.log("Nº entero: " + numEntero + " " + pNumentero2.test(numEntero));
console.log("Nº entero: " + numEntero + " " + pNumentero3.test(numEntero));
var n = 2;
const pNumreal = /^[+-]?\d+([,.]\d+)?$/;
const pNumreal2 = /^(\-)?[1-9]\d{0,7}(\,[0-9]{1,4})?$/;
var numReal = "-1,0";
console.log("Nº real: " + numReal + " " + pNumreal.test(numReal));
console.log("Nº real: " + numReal + " " + pNumreal2.test(numReal));
const patron = /^\-?[1-9]\d{0,7}(\,[0-9]{1,4})?([\+\-\*\/=])?$/;
let valor = "-1,0";
console.log("Clic: " + valor + " " + patron.test(valor));
//# sourceMappingURL=patterns.js.map